parameters:
  charset: 'UTF-8'

services:
  context:
    class: 'Symfony\Component\Routing\RequestContext'
  matcher:
    class: 'Symfony\Component\Routing\Matcher\UrlMatcher'
    arguments: [%routes%, '@context']
  request.stack:
    class: 'Symfony\Component\HttpFoundation\RequestStack'
  resolver:
    class: 'Symfony\Component\HttpKernel\Controller\ControllerResolver'
  listern.router:
    class: 'Symfony\Component\HttpKernel\EventListener\RouterListener'
    arguments: ['@matcher', '@request.stack']
  listern.response:
    class: 'Symfony\Component\HttpKernel\EventListener\ResponseListener'
    arguments: [%charset%]
  listern.exception:
    class: 'Symfony\Component\HttpKernel\EventListener\ExceptionListener'
    arguments: ['Calendar\\Controller\\ErrorController::exceptionAction']
  listern.string_response:
    class: 'Simplex\StringResponseListener'
  dispatcher:
    class: 'Symfony\Component\EventDispatcher\EventDispatcher'
    calls:
      - [addSubscriber, ['@listern.router']]
      - [addSubscriber, ['@listern.response']]
      - [addSubscriber, ['@listern.exception']]
      - [addSubscriber, ['@listern.string_response']]
  framework:
    class: 'Simplex\Framework'
    arguments: ['@dispatcher', '@resolver']